#!/usr/bin/env groovy
pipeline{
    agent none
    stages{
         stage('Pull request') {
        sh 'git checkout -b master  origin/master'
        sh 'hub pull-request -b origin/master'
    }
    }
}